# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build, test, and deploy container app to Azure Web App - sesame-gateway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: index.docker.io/${{ secrets.DOCKER_USERNAME }}/sesame-gateway:${{ github.sha }}
          file: ./Dockerfile

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.x
          
      #- name: Check working directory
       # run: pwd
        
      - name: Check working directory and folder structure
        run: pwd && ls
        
        #kills azure lol
      #- name: Check for file
       # run: find / -name "test_valid_config.yml"

      - name: Run tests
        run: go test -coverprofile=coverage.out ./...

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: "azure"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "sesame-gateway"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_b42eeaa78e9f499382e6e8443642cdb6 }}
          images: "index.docker.io/${{ secrets.DOCKER_USERNAME }}/sesame-gateway:${{ github.sha }}"
