---
server:
  port: 3333
  certFile: ./cert/server.crt
  keyFile: ./cert/server.key
---
postgres:
  pgHost: sesame.postgres.database.azure.com
  pgDatabase: userDB
  pgUser: user
  pgPassword: Tiniwo18
  pgTimeout: 3
---
proxy:
  - path: /get
    host: http://localhost:1500
    methods:
      - GET
  - path: /post
    host: http://localhost:2000
    methods:
      - POST
  - path: /yes
    host: http://localhost:3000